version: '3.7'

services:
  sample:
    container_name: pipeline
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    command: npm start
